version: '3.3'

services:
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend # a rede que deve se conectar neste serviço

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend # a rede que deve se conectar neste serviço

volumes:
  db_data: {}
networks: # declarando a rede
  backend:
    driver: bridge